databases:

  - name: beerblog
    collections:
     - name: beer
       fields:
        - name
        - rate
        - manufacturer
        - alcohol
        - ibu
        - review
        - others
        - fortress
        - not_confirmed
       # поля для полнотекстового поиска, индекс должен быть создан заранее
       index_fields:
        - name
        - rate
        - manufacturer
        - alcohol
        - ibu
        - review
        - others

     - name: wine
       fields:
        - name
        - rate
        - manufacturer
        - alcohol
        - ibu
        - review
        - others
        - fortress
        - not_confirmed
       index_fields:
        - name
        - rate
        - manufacturer
        - alcohol
        - ibu
        - review
        - others


  - name: quiz
    collections:
     - name: admin
       fields:
        - login
        - password
     - name: quiz_questions
       fields:
        - text
        - answer
        - complexity
        - category
       index_fields:
        - text
        - answer
        - complexity
        - category