databases:

  - name: beerblog
    collections:
     - name: bb_beer
       fields:
        - name
        - rate
        - manufacturer
        - gravity
        - ibu
        - review
        - others
        - fortress
       index_fields:
        - name
        - rate
        - manufacturer
        - gravity
        - ibu
        - review
        - others


  - name: quiz
    collections:
     - name: admin
       fields:
        - login
        - password
     - name: quiz_questions
       fields:
        - text
        - answer
        - complexity
        - category
       index_fields:
        - text
        - answer
        - complexity
        - category