databases:

  - name: beerblog
    collections:
     - name: beerblog_bb_beer
       fields:
        - name
        - rate
        - manufacturer
        - gravity
        - ibu
        - review
        - others
        - photos
     - name: beerblog_vodka
       fields:
        - name
        - rate
        - manufacturer
        - gravity
        - ibu
        - review
        - others
        - photos
     - name: beerblog_whisky
       fields:
        - name
        - rate
        - manufacturer
        - gravity
        - ibu
        - review
        - others
        - photos


     - name: post
       fields:
        - name

  - name: another_site
    collections:
     - name: articles
       fields:
        - name